server:
  port: 8003

spring:
  application:
    name: hospital-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hospital-database
    username: postgres
    password: changeme
springdoc:
  swagger-ui:
    path: /swagger-ui-hospital.html
    operations-sorter: method

