server:
  port: 8001

spring:
  application:
    name: patient-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/patient-database
springdoc:
  swagger-ui:
    path: /swagger-ui-patient.html
    operations-sorter: method

