server:
  port: 8001

spring:
  application:
    name: patient-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/patient-database
    username: postgres
    password: changeme
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  #springdoc.swagger-ui.path=/swagger-ui-custom.html
  #springdoc.swagger-ui.operationsSorter=method
springdoc:
  swagger-ui:
    path: /swagger-ui-patient.html
    operations-sorter: method

