spring:
  application:
    name: bloom-demo
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeme
springdoc:
  swagger-ui:
    path: /swagger-ui-bloom-demo.html
    operations-sorter: method
